  version: "3.3"

  services:
    mysql:
      container_name: mysql
      image: mysql:5.6
      restart: always
      ports:
        - "3307:3306"
      volumes:
        - mysql_db_data:/var/lib/mysql
      environment:
        #MYSQL_HOST: "192.168.66.112"
        MYSQL_USER: "root"
        MYSQL_ROOT_PASSWORD: "123"
        MYSQL_PASSWORD: "123"

    adminer_container:
      image: adminer:4.7.6
      environment:
        ADMINER_DEFAULT_SERVER: "mysql"
      ports:
        - "8080:8080"
      links:
        - mysql

  volumes:
    mysql_db_data:

